### ISSUE TITLE
Broken API in EPICS 7

### ISSUE THREAD

**Issue by mfurseman** [Araneidae/epicsdbbuilder#1]
Hi Michael,

I've been looking at using the pythonIOC with a recent release of EPICS.

From EPICS 7.0.2.1 dbGetFieldType was removed, we can instead use dbGetFieldTypeString, which was introduced in R3.15.2. The change https://github.com/mfurseman/epicsdbbuilder/commit/16b28810ece67982e6528288c0f9e56720d74545 fixes EPICS 7, but will break compatibility with versions before R3.15.2. It seems some ugly changes would be required to maintain backwards compatibility.

**Comment by Araneidae** [comment]
Why not create a replacement function in `mydbstatic.py` that has the appropriate common behaviour and which calls either `dbGetFieldType` or `dbGetFieldTypeString` as appropriate?  This would require some clunky fallback behaviour in `mydbstatic.py`, but then it already has to do this for `dbVerify`.  I so wish the EPICS developers would leave the core APIs alone ... if only there *was* a core API defined.

Speaking of compatibility ... I see that `dbGetFieldType` returns a `c_int` whereas `dbGetFieldTypeString` returns a `c_char_p` ... so what happens downstream to this data?

It gets gathered into `ValidateDbField.__FieldInfo`, which is returned by `ValidateDbField.FieldInfo`, which is republished as `Record.FieldInfo` ... at which point it appears to be never used.

`FieldInfo` is not documented in the `docs` directory and appears to not be used.  I suggest dropping this altogether, which is a much simpler solution to our problem!

**Comment by Araneidae** [comment]
Ok, I've pushed a commit to a new https://github.com/Araneidae/epicsdbbuilder/tree/pruned branch.  This is completely untested for the moment, but let me know if it works for you.  I'll try and come back to this towards the end of the month.

**Comment by mfurseman** [comment]
Thanks, I can confirm that this is working in R7.0.3.

Could any users of epicsdbbuilder be accessing FieldInfo?

**Comment by Araneidae** [comment]
Well, I have two projects that use epicsdbbuilder: https://github.com/Araneidae/epics_device and https://github.com/Araneidae/pythonIoc, and neither of them reference `FieldInfo`.  It's not documented, so I feel reasonably comfortable in dropping it.

**Comment by Araneidae** [comment]
It's worth noting where `FieldInfo` comes from in the first place.  The epicsdbbuilder project is drived from a massively cut down version of https://github.com/Araneidae/iocbuilder, and this *does* use `FieldInfo` for its interactive editing of IOC definitions (the so called `xeb` tool).

I'll leave this issue open until after my IBIC conference.

**Comment by mfurseman** [comment]
Thanks for the new release!
